services:
  - type: web
    name: shopify-ai-agent-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: VITE_SHOPIFY_STORE
        sync: false
      - key: VITE_SHOPIFY_CLIENT_SECRET
        sync: false
      - key: VITE_FRONTEND_URL
        sync: false

  - type: web
    name: shopify-app-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_API_URL
        fromService:
          name: shopify-app-backend
          type: web
          property: url 
          property: url 